export const CITIES = [
    { label: "An Giang", value: "EPSG:_An-Giang" },
    { label: "Bà Rịa - Vũng Tàu", value: "EPSG:_Bà-Rịa-Vũng-Tàu" },
    { label: "Bắc Cạn", value: "EPSG:_Bắc-Cạn" },
    { label: "Bắc Giang", value: "EPSG:_Bắc-Giang" },
    { label: "Bạc Liêu", value: "EPSG:_Bạc-Liêu" },
    { label: "Bắc Ninh", value: "EPSG:_Bắc-Ninh" },
    { label: "Bến Tre", value: "EPSG:_Bến-Tre" },
    { label: "Bình Định", value: "EPSG:_Bình-Định" },
    { label: "Bình Dương", value: "EPSG:_Bình-Dương" },
    { label: "Bình Phước", value: "EPSG:_Bình-Phước" },
    { label: "Bình Thuận", value: "EPSG:_Bình-Thuận" },
    { label: "Cà Mau", value: "EPSG:_Cà-Mau" },
    { label: "Cao Bằng", value: "EPSG:_Cao-Bằng" },
    { label: "Cần Thơ", value: "EPSG:_TP-Cần-Thơ" },
    { label: "Đà Nẵng", value: "EPSG:_TP-Đà-Nẵng" },
    { label: "Đắc Nông", value: "EPSG:_Đắc-Nông" },
    { label: "Đắk Lắk", value: "EPSG:_Đắk-Lắk" },
    { label: "Điện Biên", value: "EPSG:_Điện-Biên" },
    { label: "Đồng Nai", value: "EPSG:_Đồng-Nai" },
    { label: "Đồng Tháp", value: "EPSG:_Đồng-Tháp" },
    { label: "Gia Lai", value: "EPSG:_Gia-Lai" },
    { label: "Hà Giang", value: "EPSG:_Hà-Giang" },
    { label: "Hà Nam", value: "EPSG:_Hà-Nam" },
    { label: "Hà Nội", value: "EPSG:_TP-Hà-Nội" },
    { label: "Hà Tĩnh", value: "EPSG:_Hà-Tĩnh" },
    { label: "Hải Dương", value: "EPSG:_Hải-Dương" },
    { label: "Hải Phòng", value: "EPSG:_TP.-Hải-Phòng" },
    { label: "Hậu Giang", value: "EPSG:_Hậu-Giang" },
    { label: "Hoà Bình", value: "EPSG:_Hoà-Bình" },
    { label: "Hồ Chí Minh", value: "EPSG:_TP-Hồ-Chí-Minh" },
    { label: "Hưng Yên", value: "EPSG:_Hưng-Yên" },
    { label: "Khánh Hoà", value: "EPSG:_Khánh-Hoà" },
    { label: "Kiên Giang", value: "EPSG:_Kiên-Giang" },
    { label: "Kon Tum", value: "EPSG:_Kon-Tum" },
    { label: "Lai Châu", value: "EPSG:_Lai-Châu" },
    { label: "Lâm Đồng", value: "EPSG:_Lâm-Đồng" },
    { label: "Lạng Sơn", value: "EPSG:_Lạng-Sơn" },
    { label: "Lào Cai", value: "EPSG:_Lào-Cai" },
    { label: "Long An", value: "EPSG:_Long-An" },
    { label: "Nam Định", value: "EPSG:_Nam-Định" },
    { label: "Nghệ An", value: "EPSG:_Nghệ-An" },
    { label: "Ninh Bình", value: "EPSG:_Ninh-Bình" },
    { label: "Ninh Thuận", value: "EPSG:_Ninh-Thuận" },
    { label: "Phú Thọ", value: "EPSG:_Phú-Thọ" },
    { label: "Phú Yên", value: "EPSG:_Phú-Yên" },
    { label: "Quảng Bình", value: "EPSG:_Quảng-Bình" },
    { label: "Quảng Nam", value: "EPSG:_Quảng-Nam" },
    { label: "Quảng Ngãi", value: "EPSG:_Quảng-Ngãi" },
    { label: "Quảng Ninh", value: "EPSG:_Quảng-Ninh" },
    { label: "Quảng Trị", value: "EPSG:_Quảng-Trị" },
    { label: "Sóc Trăng", value: "EPSG:_Sóc-Trăng" },
    { label: "Sơn La", value: "EPSG:_Sơn-La" },
    { label: "Tây Ninh", value: "EPSG:_Tây-Ninh" },
    { label: "Thái Bình", value: "EPSG:_Thái-Bình" },
    { label: "Thái Nguyên", value: "EPSG:_Thái-Nguyên" },
    { label: "Thanh Hoá", value: "EPSG:_Thanh-Hoá" },
    { label: "Thừa Thiên - Huế", value: "EPSG:_Thừa-Thiên-Huế" },
    { label: "Tiền Giang", value: "EPSG:_Tiền-Giang" },
    { label: "Trà Vinh", value: "EPSG:_Trà-Vinh" },
    { label: "Tuyên Quang", value: "EPSG:_Tuyên-Quang" },
    { label: "Vĩnh Long", value: "EPSG:_Vĩnh-Long" },
    { label: "Vĩnh Phúc", value: "EPSG:_Vĩnh-Phúc" },
    { label: "Yên Bái", value: "EPSG:_Yên-Bái" }
];

export const INITIAL_COORDINATES = [
    { id: 1, x: '1196048.346', y: '601786.223' },
    { id: 2, x: '1196045.42', y: '601788.95' },
    { id: 3, x: '1196032.985', y: '601775.32' },
    { id: 4, x: '1196031.68', y: '601773.89' },
    { id: 5, x: '1196034.63', y: '601771.189' },
    { id: 6, x: '1196035.911', y: '601772.593' },
    { id: 7, x: '1196048.346', y: '601786.223' },
];
